### ISSUE TITLE
Please don't show not available resources in collapsible navigation

### ISSUE THREAD

**Issue by RazmikSaghoyan** [dcasia/collapsible-resource-manager#10]
on CollapsibleResourceManager.php class, into private method resolveResources() please add another check on availableForNavigation(). ex:
if ($resource::authorizedToViewAny(request()) && $resource::availableForNavigation(request())) {
        return [
                    'icon' => method_exists($resource, 'icon') ? $resource::icon() : null,
                    'label' => is_numeric($key) ? $resource::label() : $this->translateKey($key),
                    'route' => $resource::uriKey()
        ];
}

Now if on resource availableForNavigation() method is returned false, the navigation menu is showing.

Thanks

**Comment by RazmikSaghoyan** [comment]
@milewski @samueljess

**Comment by milewski** [comment]
@RazmikSaghoyan can you submit a PR with this change?

**Comment by RazmikSaghoyan** [comment]
@milewski thanks for fix :+1:

**Comment by milewski** [comment]
Oh yeah! I just pushed a fixed for that forgot to notify here 👍

**Comment by RazmikSaghoyan** [comment]
Great thanks
