### ISSUE TITLE
Vertical menu?

### ISSUE THREAD

**Issue by scramatte** [dcasia/collapsible-resource-manager#100]
Hi,

On your screenshot I can see a vertical menu with icons,  I haven't seen such feature in the Nova official documentation.
I've got an app with many many menus and submenus

**Comment by scramatte** [comment]
It's works ... It's simply amazing ! Thank you for this package !

**Comment by milewski** [comment]
Did you figured out how to show the vertical menu? All you need to do is create menu sections and menu groups, I didn't document but you can also include lens, dashboards, external links they all works

**Comment by scramatte** [comment]
I've seen it  ! It's works great

**Comment by tenreiro** [comment]
@milewski I'm trying to use your package, I have installed it via composer. I'm using laravel nova 4.22.2.

After I install this package, the menu simply disappears. Am I doing anything wrong? Can you help me with this? I have tried everythin... I really need this feature.

![image](https://github.com/dcasia/collapsible-resource-manager/assets/225412/e2810737-0e75-4b1d-867e-30d7298a745c)

**Comment by milewski** [comment]
Can you upgrade your nova to version 4.33.3?

**Comment by milewski** [comment]
Because this is an older version of nova, the latest version has only been tested against the latest version of nova (4.33.3).. 

Perhaps you could also downgrade this package to an earlier version [v2.1.0](https://github.com/dcasia/collapsible-resource-manager/releases/tag/v2.1.0) which might work for you

**Comment by tenreiro** [comment]
Perfect!!! I will try that!🙏

A quarta, 22/05/2024, 07:36, Rafael Milewski ***@***.***>
escreveu:
