### ISSUE TITLE
Append HTML to the top of the collapsible block? 

### ISSUE THREAD

**Issue by scramatte** [dcasia/collapsible-resource-manager#102]
Hi,

Does it possible to append HTML to set a title, with some abstract about the section on the top of collapsible block? 

![imagen](https://github.com/dcasia/collapsible-resource-manager/assets/188766/0692237b-a56e-41be-b68a-ecc870ba2f3c)

something like in the screenshot

My app has lots of module and when you click on the section , it's not very clear which section is open.
Moreover it still appears selected the old section until you click a group or an item.

Regards

**Comment by milewski** [comment]
The same issue as this other issue https://github.com/dcasia/collapsible-resource-manager/issues/101#issuecomment-1758841474 we need to have the `Metable` trait included in all the menu classes to be able to extend it beyond what Nova has out of the box, closing this for now but if you manage to convince nova team to include it let me know so I can work on it.

**Comment by milewski** [comment]
I opened an issue here https://github.com/laravel/nova-issues/discussions/5960
