### ISSUE TITLE
Incorrect path MenuSection 

### ISSUE THREAD

**Issue by scramatte** [dcasia/collapsible-resource-manager#104]
Hi,

When you set path to a MenuSection   "app" is appended twice  to the URL resulting incorrect path

```php
   MenuSection::make('tool')
            ->path('/csv-import')
            ->icon('upload');
```
create path 

`/app/app/csv-import `

![imagen](https://github.com/dcasia/collapsible-resource-manager/assets/188766/a2b0689a-d4ff-458a-ab09-fc880e91ac8b)

I've test with a fresh Nova Install and the issue is related to your package.

Regards

**Comment by milewski** [comment]
Is `/app` your `Nova Path` ?

**Comment by milewski** [comment]
Fixed and released here [v2.0.3](https://github.com/dcasia/collapsible-resource-manager/releases/tag/v2.0.3)

**Comment by milewski** [comment]
Can you paste your `Nova::mainMenu(function (Request $request) {})` config

**Comment by scramatte** [comment]
Hi,

My app has various module that construct their own menu 
But It occurs with default menu too or with a very simple as bellow:

```php
        Nova::mainMenu(function (Request $request, Menu $menu) {
            $menu->items->forget(1); // remove Resources MenuSection
             return $menu;
        });
```
I'm practically sure that is a regression as in the previous version it was ok.
I'm  going to try with previous one and I come back to you.

Regards

**Comment by milewski** [comment]
I think I found the issue, it was due that if you had a MenuSection and did not specify an icon it had a chance to crash.. fixed it on the latest version
