### ISSUE TITLE
Dashboards link doesn't works

### ISSUE THREAD

**Issue by scramatte** [dcasia/collapsible-resource-manager#109]
Hi,

If you click on Dashboards icon  it doesn't works as expected.
It open collapsed menu (that is empty) and doesn't show dashboards

![imagen](https://github.com/dcasia/collapsible-resource-manager/assets/188766/7150c1c6-67f0-4630-9165-7ffb48fc180f)

Regards

**Comment by milewski** [comment]
This is what I have on my local:

<img width="1223" alt="image" src="https://github.com/dcasia/collapsible-resource-manager/assets/2874967/69ffee12-ad77-43b3-85e7-7436892fe6bc">

... and it works when I click ... 

do you have it setup differently?

**Comment by scramatte** [comment]
With the following it doesn't works

```
Nova::mainMenu(function (Request $request, Menu $menu) {
            $menu->items->forget(1); 
            return $menu;
});
```

If you add MenuSection manually it works well, but if you use original nova menu it doesn't

**Comment by milewski** [comment]
Ahh I think I finally got what you mean, you are saying like not defining each menu manually but let nova auto generate it for you, I think I know why this might happen, gonna fix soon
