### ISSUE TITLE
Menu doesn't scroll on mobile device

### ISSUE THREAD

**Issue by scramatte** [dcasia/collapsible-resource-manager#113]
Hi,

Menu doesn't scroll vertically on mobile device. I've tested it on iphone 8 with iOS 16.3 and on Oppo Android 11
Regards

**Comment by milewski** [comment]
Can you test this: https://github.com/dcasia/collapsible-resource-manager/pull/115

**Comment by scramatte** [comment]
Hi, I've test it on both platforms and the scroll works only if it's selected/focus a menu item

**Comment by scramatte** [comment]
Any update?

**Comment by scramatte** [comment]
Hi, any update on this issue?

**Comment by scramatte** [comment]
Hi,

This issue has been fixed in my fork  (https://github.com/operativeit/collapsible-resource-manager)  and in the PR #127 
Regards
