### ISSUE TITLE
Menu issue on mobile devices

### ISSUE THREAD

**Issue by scramatte** [dcasia/collapsible-resource-manager#116]
Hi,

On mobile device the menu is totally collapsed by default.
When you click on  open (burger icon),  the complete menu is open and not only the small icons part. So in my case as first item (dashboards) is direct link I've got an empty menu.

![imagen](https://github.com/dcasia/collapsible-resource-manager/assets/188766/4d0832e7-6c4c-4f4d-b1f7-4ebf1ea65aa1)

Regards

**Comment by scramatte** [comment]
Any update?

**Comment by philipbaginski** [comment]
The same. On mobile works very different than on desktop. In addition when clicking link to resource menu is still open and needs to be close manually.

**Comment by scramatte** [comment]
Hi, any update on this issue?

**Comment by scramatte** [comment]
Hi,

This issue has been fixed in my fork  (https://github.com/operativeit/collapsible-resource-manager)  and in the PR #127 
Regards
