### ISSUE TITLE
Breaking word to a new line if menu item is too long

### ISSUE THREAD

**Issue by kavanpancholi** [dcasia/collapsible-resource-manager#117]
When the text of the menu item is long, it doesn't break text into new line.

<img width="323" alt="image" src="https://github.com/dcasia/collapsible-resource-manager/assets/5137072/fab6999d-569b-440a-819a-fe9f68753641">

This is because of `whitespace-nowrap` class in the `Menu.vue`.
Removing that class fixes the issue.

**Comment by kavanpancholi** [comment]
Fixed it using this PR: https://github.com/dcasia/collapsible-resource-manager/pull/118

**Comment by milewski** [comment]
Thanks [v2.0.6](https://github.com/dcasia/collapsible-resource-manager/releases/tag/v2.0.6)
