### ISSUE TITLE
Enable/Disable Toggle Switch

### ISSUE THREAD

**Issue by khitas** [dcasia/collapsible-resource-manager#123]
Can you please add a switch to expand/collapse the resources menu;

**Comment by milewski** [comment]
can you give me an example of what you mean? it is already possible to expand/collapse by clicking on the items of the menu...

**Comment by khitas** [comment]
Something like this, so the user can expand/collapse entire menu

![sidebar](https://github.com/dcasia/collapsible-resource-manager/assets/1069228/9c2baa1e-392a-4243-b806-a83ad25d6780)

**Comment by scramatte** [comment]
Hi,

This feature has  implemented in my fork  (https://github.com/operativeit/collapsible-resource-manager)  and in the PR #127 
Regards
