### ISSUE TITLE
Using internal or external link, not working

### ISSUE THREAD

**Issue by fbingha** [dcasia/collapsible-resource-manager#13]
Defining an internal link as such:

                [
                    'title'     => 'Menu Item',
                    'expanded'  => false,
                    'resources' => [
                       'Item Name' => '/item'
                    ]
                ],

This causes the menu category to not show up at all. Same thing happens if I change it to

'Item Name' => 'https://www.foo.com'

Am I not understanding the internal / external functionality?

**Comment by milewski** [comment]
Just tried and yeah its a regression, the way it should work 

```php
[
    'title'     => 'Menu Item',
    'expanded'  => false,
    'resources' => [
        'Internal' => '/item', // this opens on the same tab, and no icon is added
        'External' => 'https://...' // this add an extra icon beside the link and opens in a new tab
    ]
],
```

I will look into it see what went wrong on the latest version

**Comment by milewski** [comment]
@fbingha fixed on version [v0.1.9](https://github.com/dcasia/collapsible-resource-manager/releases/tag/v0.1.9)

**Comment by fbingha** [comment]
Okay it is working now but one more request. I want to use the link to a Nova tool, so I put the path and it works but it browser page reloads since it isn't using the vue route to open the tool. Can you add an option to use a vue route so the single page app isn't broken when following the link?

**Comment by fbingha** [comment]
Looking at the code, going to be a bit more complicated to add links to tools as they will also need to respect permissions. The goal is to remove the links that tools add and just have navbar entries from this tool. If the config could support (a) being told what permission(s) to check and (b) what vue route to load then I think it could be done without knowing anything specific about the tool being linked to.

**Comment by fbingha** [comment]
Another way to do this requires changing nothing in the config.

I created resources for each of my tools so that permissions and uriKey could be utilized. The only issue is in ResourceList.vue. When a resource is found, it is assumed the the 'index' route is to be used for the resource.route. So just need away to have the :to{} params name and params links be read from the resource object.

:to="{ name: resource.link , params: resource.params  }

**Comment by fbingha** [comment]
I made some quick hacks to my branch https://github.com/fbingha/collapsible-resource-manager

Here, I already had "fake" resources for my Tools as I was already putting them into the sidebar along with other resources that they grouped with. I use view overrides to remove the normal navigation links that tools put into the sidebar.

So in my "fake" resources, I added a two class variables:

    public static $nonIndex = true;

    public static $params = [];

The first tells your tool not to use the index route, instead use the urikey as the route and second a params in the event the route has params, which some of mine do.

With this, I now have all of the tools in the menu where they belong.

Using the fake resource also allows me to use the existing permissions check.

I still think it would probably be easier for you to adjust your config so that with the resource group one could provide the route name, the params, and the permissions to check and not create a fake resource as I have done.

**Comment by milewski** [comment]
@fbingha Im looking into your fork, I am not sure why you changed this if condition with index/params: https://github.com/fbingha/collapsible-resource-manager/blob/master/src/CollapsibleResourceManager.php#L111

The way im seeing it working would be something along this line:

```php
'resources' => [
    \App\Nova\Page::class, 
    'Internal Link' => '/custom/route',
    'Tool' => [
        'params' => [ 'a' => '123'] ,
        'name' => 'yyy'
     ]
],
```

which would then be given to the `route-link` like this: 

```js
<router-link :to="{ name: resource.name, params: resource.params }"/>
```

But what im unsure is how a user would know the route name/params of a tool without digging up the package and figuring it out on their own?

**Comment by milewski** [comment]
And the permission could also be solved by perhaps sending the tool class itself to the config:

```
'resources' => [
    \App\Nova\Page::class, 
    'Internal Link' => '/custom/route',
    'Tool Label' => [
        'tool' => ToolName::class,
        'params' => [ 'a' => '123'] ,
        'name' => 'yyy'
     ]
],
```

**Comment by milewski** [comment]
With this approach would also allow users to create internal links that don't go to index listing page but perhaps detail, or edit.

```
'resources' => [
    \App\Nova\Page::class, 
    'Internal Link' => '/custom/route',
    'Resource Label' => [
        'resource' => ResourceName::class,
        'params' => [ 'resourceName' => ResourceName::uriKey(), 'id' => 3 ] ,
        'name' => 'detail'
     ]
],
```

It`s a bit verbose and requires the user knowing all the underlying params but given enough examples one could find a way around it ...

**Comment by fbingha** [comment]
Looks good to me

**Comment by milewski** [comment]
@fbingha the new version supports everything you were trying to do on your branch [v1.0.0](https://github.com/dcasia/collapsible-resource-manager/releases/tag/v1.0.0) 🎉
