### ISSUE TITLE
Cannot read properties of undefined (reading 'isMobile')

### ISSUE THREAD

**Issue by dzandrey** [dcasia/collapsible-resource-manager#130]
I have an error
collapsible-resource-manager:2 TypeError: Cannot read properties of undefined (reading 'isMobile')
at Proxy.handler (collapsible-resource-manager:2:646852)

**Comment by nurmuhammet-ali** [comment]
+1

**Comment by web-svb** [comment]
+1

**Comment by aaronaccessvr** [comment]
👍

**Comment by aaronaccessvr** [comment]
Are there plans to fix this?
