### ISSUE TITLE
Lenses

### ISSUE THREAD

**Issue by timcv** [dcasia/collapsible-resource-manager#14]
Hi,

Do you think it would be possible to add support for lenses in the menu?

I can use the "Internal Link" example, but the link wont be marked as active and it will do a full page reload.

Kind regards
Tim

**Comment by milewski** [comment]
There was an discussion here to add the ability to set the route and params, but yet I havent got time to do this change: https://github.com/dcasia/collapsible-resource-manager/issues/13#issuecomment-546656121

**Comment by milewski** [comment]
@timcv Hi it's now possible to add links to lens pages directly on version [v1.0.0](https://github.com/dcasia/collapsible-resource-manager/releases/tag/v1.0.0) 🎉
