### ISSUE TITLE
Unknown custom element: <RouterLink>

### ISSUE THREAD

**Issue by RazmikSaghoyan** [dcasia/collapsible-resource-manager#16]
Please fix

vendor.js?id=8a0b277a131df1bccb14:91212 [Vue warn]: Unknown custom element: <RouterLink> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <ResourceList>
       <CollapseTransition>
         <CollapsibleResourceManager>
           <Root>

**Comment by milewski** [comment]
fixed version `v1.2.1`
