### ISSUE TITLE
Top Level Collapsible

### ISSUE THREAD

**Issue by bernhardh** [dcasia/collapsible-resource-manager#17]
Maybe I have overlooked something, but how to make a toplevel collapsible? I mean, I would like to have in my sidebar something like the following:

- Dashboard
- Group1 +
   - Resource1
   - Resource2
- Group2 +
   - Resource3
   - Resource4

And "Group1" and "Group2" should be collapsed by default? 

BTW: Thank you for your great package.

**Comment by milewski** [comment]
You can have something like this:

```php
TopLevelResource::make([
    'label' => null, //<--- the key is here! set this to null
    'resources' => [
        Group::make([
            'label' => 'Group1',
            'expanded' => false, //<--- collapsed by default
            'resources' => [
                Resource1::class,
                Resource2::class
            ]
        ]),
        Group::make([
            'label' => 'Group2',
            'expanded' => false,
            'resources' => [
                Resource3::class,
                Resource4::class,
            ]
        ]),
    ]
]),
```

**Comment by milewski** [comment]
Sorry closed by mistake 😆

**Comment by bernhardh** [comment]
Ok, setting `label` to null, does the trick, but it  doesn't look like a "regular" toplevel menu entry.

![image](https://user-images.githubusercontent.com/642292/70602557-ff743f00-1bf4-11ea-918f-d72f9b99f50c.png)

**Comment by milewski** [comment]
Ah misunderstood you actually want the Top-level menu itself to be collapsable, currently, there is no option to do accomplish that, only sub-items from the top-level menu are collapsible, however, wouldn't be hard to create a new TopLevelMenuClass that has the ability to be collapsed

**Comment by matovu-ronald** [comment]
Thanks very much for this collapsible package, I still up to now don't get why nova developers ignore such features in the making of the admin panel yet is crucial and being used in all admin panels on the web, I would be glad to see this feature come into play, eagerly waiting for it. As in the previous comments we had you remember me talking about it.
