### ISSUE TITLE
Incorrect menu on firefox mozilla 

### ISSUE THREAD

**Issue by RazmikSaghoyan** [dcasia/collapsible-resource-manager#18]
![Screenshot_2019-12-17-19-26-31-251_org mozilla firefox](https://user-images.githubusercontent.com/28092645/71009142-31a90380-2103-11ea-8dbb-1cc65a884156.jpg)

**Comment by RazmikSaghoyan** [comment]
@milewski the issue comes from -3px top margin on icon div

**Comment by milewski** [comment]
@RazmikSaghoyan fixed on version `v1.2.2`

**Comment by RazmikSaghoyan** [comment]
@milewski thanks
