### ISSUE TITLE
How to enable CollapsibleResourceManager

### ISSUE THREAD

**Issue by GitanjaliCS** [dcasia/collapsible-resource-manager#22]
Hello,

I run below command 
"composer require digital-creative/collapsible-resource-manager" and have set menu items in NovaServiceProvider. But i got below error 
"Class 'App\Providers\CollapsibleResourceManager' not found". 

Please help me out. I have invested full time to solve this issue.

**Comment by milewski** [comment]
which version of laravel are you using?

**Comment by GitanjaliCS** [comment]
laravel 6.13.1 and latest nova v2.10.1

**Comment by milewski** [comment]
try running `composer dump-autoload`

**Comment by GitanjaliCS** [comment]
Yes have tried. Still it is not working

**Comment by milewski** [comment]
it seems the package wasn't auto-discovered, you can add `App\Providers\CollapsibleResourceManager` into your `providers` array inside your `config\app.php`

**Comment by milewski** [comment]
OK never mind you have the wrong import it should be:

```diff
- App\Providers\CollapsibleResourceManager
+ DigitalCreative\CollapsibleResourceManager\CollapsibleResourceManager
```

**Comment by GitanjaliCS** [comment]
Ok I have written below code inside app.php

'providers' => [
DigitalCreative\CollapsibleResourceManager\CollapsibleResourceManagerServiceProvider::class,
],
'aliases' => [
//What should I write in this block?
],

**Comment by milewski** [comment]
No need add the provider ... I read your first comment and I saw the `provider` keyword there so I assumed it was that issue.. but looking better you were trying to importing `CollapsibleResourceManager` but with the wrong namespace

**Comment by GitanjaliCS** [comment]
`
![screencapture-localhost-8000-nova-dashboards-main-2020-02-12-17_03_49](https://user-images.githubusercontent.com/60965982/74331483-c5bce180-4db9-11ea-84d1-620a82f6f66b.png)
`

**Comment by GitanjaliCS** [comment]
Still the same error 
Check my code
public function tools()
    {
        return [
            \Whitecube\NovaPage\NovaPageTool::make(),
            new \ClassicO\NovaMediaLibrary\NovaMediaLibrary(),
            new \Eminiarts\NovaPermissions\NovaPermissions(),
            new CollapsibleResourceManager([
                'navigation' => [
                    TopLevelResource::make([
                        'label' => 'Resources',
                        'resources' => [
                            \App\App\Nova\User::class
                        ]
                    ]),
                ]
            ])
        ];
        ];
    }

**Comment by milewski** [comment]
show me your entire file it should be `DigitalCreative\CollapsibleResourceManager\CollapsibleResourceManager` for the import

**Comment by GitanjaliCS** [comment]
Ok. I imported DigitalCreative\CollapsibleResourceManager\CollapsibleResourceManager in NovaServiceProvider.php
It works fine.
Thank you so much
