### ISSUE TITLE
Hide TopLevelResource label and icon when all resources in the group hidden

### ISSUE THREAD

**Issue by ITango** [dcasia/collapsible-resource-manager#26]
I'm using permissions to show/hide resources to users. Sometimes, it happens that a given user is not allowed to see all the resources in the group(s) under one of the TopLevel menus.

I am able to hide all the resources, however, the label and icon of the TopLevelResource as still visible, as on the attached screenshot.

Is it possible to hide the TopLevelResource menu in those cases?
<img width="258" alt="Screen Shot 2020-03-26 at 2 26 14 pm" src="https://user-images.githubusercontent.com/11846530/77613873-30436e80-6f6f-11ea-9e48-12095b425afa.png">

**Comment by cord** [comment]
same issue here

**Comment by omarmatijas** [comment]
A posible workarround is to use _->cansee_ method for TopLevel element.

**Comment by blackfyre** [comment]
Can confirm the existence of this bug.
In our case it only shows itself the `TopLevelResource` has an empty `Group` inside of it.

**Comment by scramatte** [comment]
Same issue here. 
Might be using canSee method it's possible to check if at least a child has permission ?

**Comment by cerobox** [comment]
I solve using a CSS class.

`.leading-tight:empty {
    display: none;
}`

**Comment by milewski** [comment]
This issue is no longer present on the latest version [v2.0.0](https://github.com/dcasia/collapsible-resource-manager/releases/tag/v2.0.0)
