### ISSUE TITLE
Gapping or blanks when user not authorized to see resource.

### ISSUE THREAD

**Issue by rayleroux** [dcasia/collapsible-resource-manager#27]
Howdy.

Having some trouble with blank spaces when all the models in a Group::make are made not visible to the logged in user by a Laravel Policy.

Looking at the HTML source, it appears the li tags are being created but contain no group div tags within them.

**Comment by gabrielesbaiz** [comment]
If you use `->canSee()` directly to Group, there is no blank space.

**Comment by Saifallak** [comment]
@dcasia that would be awesome, if you can look into this.
this part is needed in the system.

**Comment by milewski** [comment]
Fixed here: [v1.4.0](https://github.com/dcasia/collapsible-resource-manager/releases/tag/v1.4.0)
