### ISSUE TITLE
indent group menu items 

### ISSUE THREAD

**Issue by cord** [dcasia/collapsible-resource-manager#28]
Having a lot of grouped menu items with icons now - It is hard to distinguish between the group label and the grouped items.

It would be great to have items with icons indented, so the icons start where the text starts now.

A flexible way to achieve would be to introduce a "class" parameter to each Resource Type so we can add a CSS class and style it.

**Comment by vesper8** [comment]
Would love to see this added too.. in the meantime have you figured out a workaround @cord ?

**Comment by vesper8** [comment]
I was able to add this by generating a custom theme and adding this bit of css

```
.top_level ul li ul li {
  margin-left: 5px;
}
```

**Comment by cord** [comment]
works here - changed to `1.5rem` for being consistent with the nova styles:

```
        .top_level ul li ul li {
            margin-left: 1.5rem;
        }
```

**Comment by milewski** [comment]
Latest version has been redesigned, I believe there wont be such confusion anymore [v2.0.0](https://github.com/dcasia/collapsible-resource-manager/releases/tag/v2.0.0)
