### ISSUE TITLE
allow to add tools

### ISSUE THREAD

**Issue by cord** [dcasia/collapsible-resource-manager#3]
The option to add tools to the menu would be great (think you should rename the package to menu manager)

**Comment by milewski** [comment]
I think with the approach I took with this package wouldn't make it possible to have tools injected within it, as tools are usually free to do their own logic on the menu it exposes on the navigation which would make it difficult to cover every use case. 

So I think this request is a bit out of scope for now

**Comment by cord** [comment]
I see, would it be possible to support "any url" for items? (not limited to resource routes)

**Comment by milewski** [comment]
@cord version `v0.1.3` also supports adding custom external/internal URLs
