### ISSUE TITLE
Cards not updating

### ISSUE THREAD

**Issue by cord** [dcasia/collapsible-resource-manager#31]
This is probably not a direct issue of this package, but anyways:

When linking directly to resources like this: 
```
NovaResource::make(\App\Nova\User::class)->detail(1)->label('User 1'),
NovaResource::make(\App\Nova\User::class)->detail(2)->label('User 2'),
```
and navigating between them, the cards are not updated - I use `Ericlagarda\NovaTextCard` to display some resource specific information.

Any idea why this happens and how to solve it?

**Comment by milewski** [comment]
No longer an issue on the latest version [v2.0.0](https://github.com/dcasia/collapsible-resource-manager/releases/tag/v2.0.0)
