### ISSUE TITLE
After install: Error Class 'App\Providers\CollapsibleResourceManager' not found 

### ISSUE THREAD

**Issue by NowakAdmin** [dcasia/collapsible-resource-manager#34]
Just after installation i have this error, added to nova tool.

I also tried add any of those, cannot find good way
        use DigitalCreative\CollapsibleResourceManager;
use DigitalCreative\CollapsibleResourceManager\TopLevelResource;
use DigitalCreative\CollapsibleResourceManager\CollapsibleResourceManager;
use DigitalCreative\CollapsibleResourceManager\CollapsibleResourceManagerServiceProvider;
use DigitalCreative\CollapsibleResourceManager\TopLevelResource;
use App\Providers\CollapsibleResourceManager;

**Comment by milewski** [comment]
`use DigitalCreative\CollapsibleResourceManager\CollapsibleResourceManager` should be the right one

**Comment by NowakAdmin** [comment]
After adding 
`use DigitalCreative\CollapsibleResourceManager\CollapsibleResourceManager`
There are another error:
`Error
Class 'App\Providers\TopLevelResource' not found`
Adding:
`use DigitalCreative\CollapsibleResourceManager\TopLevelResource;` or
`use DigitalCreative\CollapsibleResourceManager\CollapsibleResourceManager\TopLevelResource;`
not solve problem.

Nova: 3.9.1 , Laravel 7.28.3

**Comment by milewski** [comment]
The class name should be:

```
use DigitalCreative\CollapsibleResourceManager\CollapsibleResourceManager;
use DigitalCreative\CollapsibleResourceManager\Resources\TopLevelResource;
```

Your IDE can automatically import these files for you (VS-code, PHPSTORM, NetBeans etc..) no need to manually import classes in 2020....

**Comment by NowakAdmin** [comment]
Sorry i just use basic Notepad++ it doesn't have auto class importer

I think You can just add thoose 2 lines to readme for dinosaurs like me.

**Comment by milewski** [comment]
I see, another way to figure out the class names is by finding the file directly and reading the namespace on the top of it:

https://github.com/dcasia/collapsible-resource-manager/blob/master/src/Resources/TopLevelResource.php#L3
