### ISSUE TITLE
Reserved prop name "style"

### ISSUE THREAD

**Issue by dgoldstein89** [dcasia/collapsible-resource-manager#35]
I'm getting the following console warning:
 `"style" is a reserved attribute and cannot be used as component prop.`
I believe renaming the prop "style" to "styles" in CollapsibleIndicator.vue should fix this.

**Comment by rossedu** [comment]
Me too

**Comment by fernandoherlo** [comment]
+1

**Comment by slonomag** [comment]
The same issue :(

**Comment by goldmerc** [comment]
Yep, this small issue is still live.

**Comment by tschmidiger** [comment]
+1

**Comment by milewski** [comment]
I think the problem is not with this package, there is no prop called `style` on any .vue files.. I also dont have this error on any project I use this package.. Perhaps you all have another package in commun that is trying to modify this package somehow?

**Comment by tschmidiger** [comment]
The problem has been solved in this [commit](https://github.com/dcasia/collapsible-resource-manager/commit/635b79b199a27e03c730e9962ae83148323b3b5b) - but this commit has not been included in a release yet.

**Comment by milewski** [comment]
Completely forgot it... I have published a new version now `1.3.0` should have this fix included then
