### ISSUE TITLE
remember_menu_state doens't work

### ISSUE THREAD

**Issue by RomkaLTU** [dcasia/collapsible-resource-manager#37]
remember_menu_state doesn't work. Corresponding localStorage item not setting up. 

Laravel 8.6.0, Laravel Nova 3.10.0

**Comment by goldmerc** [comment]
This still appears to be not working. If I click any nova link which isn't in the menu, the menu resets to the default open/close state and doesn't remember the previous state.

**Comment by goldmerc** [comment]
I just noticed this pull request - #43 which fixes the issue for me.

**Comment by milewski** [comment]
Merged #43
