### ISSUE TITLE
add option for applying collapsible behaviour to existing groups

### ISSUE THREAD

**Issue by vesper8** [dcasia/collapsible-resource-manager#38]
It would be nice if the default behaviour, or this could be configurable, was to take the existing resources and groups and made the groups collapsible, without having to explicitly define all the groups and their resources. My resources are all auto-loaded and auto-detected and having to manually specify them is undesirable. Since Nova already has a mechanism for grouping resources, couldn't you just take that and apply your collapsibility to the existing groups? And if a user requires more complex scenarios then they can define it themselves?

**Comment by milewski** [comment]
The main problem I had with the default nova auto load thing was that it would add the resources and groups in undesirable order... especially if I'm using a language other than English (Chinese for example).. to implement the autoloading of the files is not hard to do.. this could be simply done on the user side. 

There was a similar issue on another package: https://github.com/dcasia/nova-inline-morph-to/issues/4 perhaps you could get some inspiration from the code snippets in there.
