### ISSUE TITLE
advanced layout

### ISSUE THREAD

**Issue by cord** [dcasia/collapsible-resource-manager#4]
Would be great to get support for a modern menu like this:

![Configuration - Welcome 2019-09-30 10-27-54](https://user-images.githubusercontent.com/158588/65861952-7e373b00-e36d-11e9-9a1c-e93e044dfde8.png)

Maybe you can join forces with:

https://github.com/laravel/nova/pull/566

**Comment by milewski** [comment]
Well, I think this is a bit off the goal of this package, I just meant to have an easy way to create collapsible groups and order the resources the way I need it to be in oppose to the alphabetical auto ordering way that the default resource manager imposes. 

It would require a completely different approach, so I think if ever try to accomplish something like that would be a work for another package 😆

**Comment by cord** [comment]
> I just meant to have an easy way to create collapsible groups and order the resources the way I need

yes!

the rest is "just" some vue + css layout work.

Clicking on the main level would set a property. Based on the property a group is shown.
