### ISSUE TITLE
Can the default Dashboard menu option be removed or edited?

### ISSUE THREAD

**Issue by terry-greenlaw** [dcasia/collapsible-resource-manager#45]
If not, what is the syntax for adding dashboards under resources?
I tried using both NovaResource:: and InternalLink::, but NovaResource:: threw errors pointing to the dashboard class file, and InternalLink wasn't doing a RouterLink, so the whole page was being redrawn.
The docs say WidgetResource:: only supports the Nova Dashboard package, so I didn't try that.

The menu in Nova is one of its weakest points, but this package goes a LONG way to fixing that. Many Thanks!

**Comment by milewski** [comment]
Yes, you can remove the default nova dashboard link:

```php
new CollapsibleResourceManager([
    'disable_default_resource_manager' => true, // set this to true..
]);
```

**Comment by terry-greenlaw** [comment]
Thanks for the quick response!

Even when explicitly setting 'disable_default_resource_manager' => true, the Dashboard menu link is still displaying for me.

            new CollapsibleResourceManager([
                'disable_default_resource_manager' => true,
                'remember_menu_state' => true,
                'navigation' => [
                    TopLevelResource::make([
                        'label' => 'Resources',
                        'icon' => null, // HTML/SVG string or callback that produces one, see below
                        'resources' => [
                            Group::make([
                                'label' => 'People',
                                'expanded' => true,
                                'resources' => [
                                    NovaResource::make(\App\Nova\Account::class),
                                    NovaResource::make(\App\Nova\Person::class),
                                ]
                            ]),
![image](https://user-images.githubusercontent.com/49298815/102989513-ba5f3a00-44e3-11eb-82f2-c5c88ad53e84.png)

I can live with the Dashboard link there if I can move custom dashboards into the Resources menu so I can have control over expanding and collapsing the list. Which resource type (NovaResource, etc.) is used to link to dashboards?

**Comment by milewski** [comment]
Oh, I misunderstood what you meant.. Yeah, it is possible to remove that.. add this to your `NovaServiceProvider` tools method:


```php
public function tools()
{

    foreach (Nova::$tools as $index => $tool) {

        if ($tool instanceof \Laravel\Nova\Tools\Dashboard) {

            unset(Nova::$tools[ $index ]);

        }

    }

}
