### ISSUE TITLE
Tool links with params

### ISSUE THREAD

**Issue by Petoches** [dcasia/collapsible-resource-manager#46]
Hi,

Trying to use RawRessource for a tool but when trying to access another id nova doesn't reload the data correctly.

Let's says i have a link to /tool/1 and a link to /tool/2

when trying to reach /tool/2 from /tool/1 the data doesn't reload on _self link i still have the data from /tool/1. 

> Yeah! but you need to define the router name/params/query manually using the `RawResource`
> 
> ```
> RawResource::make([
>     'label' => 'Your Tool',
>     'name' => 'ROUTER_NAME',
>     'params' => [ 'foo' => 'bar' ],
>     'query' => [ 'foo' => 'bar' ],
> ])
> ```
> 
> _Originally posted by @milewski in https://github.com/dcasia/collapsible-resource-manager/issues/15#issuecomment-560407930_

**Comment by milewski** [comment]
The 2 routes have the exact same name? if the only change that happens between the 2 routes is on the `query` vue will not re-render your component that's why you still get the same data

**Comment by Petoches** [comment]
Yes only the query will change, there is no way to force vue to re-render ?

**Comment by milewski** [comment]
@Petoches you can but you will need to update the code from your tool, are you able to modify it?.. if you can modify it all you need to do is add a watcher on your Vue component and instruct it to refresh the state `$route.query: () => refetchYourData..`

**Comment by Petoches** [comment]
Yes it's my own tool, i'll try that thanks for your help.
