### ISSUE TITLE
Grouping nova custom tools

### ISSUE THREAD

**Issue by Pamposgsk** [dcasia/collapsible-resource-manager#47]
Hi,
Can we also group nova custom tools in the navigation bar?
Thanks

**Comment by milewski** [comment]
Hi, see this issue: https://github.com/dcasia/collapsible-resource-manager/issues/15#issuecomment-560407930

**Comment by goldmerc** [comment]
The solution works but I notice that I have to set the params for the sidebar link to appear. So, if my tool doesn't use params, I have to set an empty array for the link to display.

**Comment by NowakAdmin** [comment]
I can;t handle to display custom tool inside RawResource, where i should put in my example 
" new \Czemu\NovaCalendarTool\NovaCalendarTool " ?


```
RawResource::make([
        'badge' => null,
        'icon' => null,
        'target' => '_self',
        'path' => null,
        'params' => [ new \Czemu\NovaCalendarTool\NovaCalendarTool ],
        'query' => [ 'foo' => 'bar' ],
         'label' => 'NovaCalendarTool',
         'name' => 'NovaCalendarTool',
])
```
or 
```
RawResource::make([
                        'badge' => null,
                        'icon' => null,
                        'target' => '_self',
                        'path' => new \Czemu\NovaCalendarTool\NovaCalendarTool,
                        'params' => [],
                        'query' => [],
                        'label' => 'NovaCalendarTool',
                        'name' => 'NovaCalendarTool',
                    ]),
```
not working

**Comment by milewski** [comment]
You shouldn't be putting `new \Czemu\NovaCalendarTool\NovaCalendarTool` on the path.. you need to manually set that path your custom tool has registered on the .vue files.. for example:

'path' => `/resources/my-custom-tool`

**Comment by NowakAdmin** [comment]
I found the way it works so i will share it here.
In file below i found proper name and path
**\vendor\czemu\nova-calendar-tool\resources\js\tool.js**
```
Nova.booting((Vue, router, store) => {
  router.addRoutes([
    {
      name: 'nova-calendar-tool',
      path: '/nova-calendar-tool',
      component: require('./components/Tool'),
    },
  ]);
})
```
Then i adapt code like this:
```
TopLevelResource::make([
     'resources' => [
            RawResource::make([
            'badge' => null,
            'icon' => null,
            'target' => '_self',
            'path' => '/nova-calendar-tool', // from tool.js
            'params' => [],
            'query' => [],
            'label' => 'Any label',
            'name' => 'nova-calendar-tool', // from tool.js
            ]),
    ],
]),
```

And it works :-)

**Comment by rgdigital** [comment]
@NowakAdmin 

This is fine if the tool is instantiated, but then $tool->renderNavigation() is still called in views/layout.blade.php, so there are double links. But if I don't instantiate the tool then the routing isn't added by the .vue file, so it doesn't work.

So if I want to move a tool into a specific resource group but leave the others, then I could just disable the renderNavigation method. But that means overriding the default template so the whole menu needs to be created via tools().

Did you find a way around this?

**Comment by rgdigital** [comment]
Got the answer from [this thread](https://github.com/dcasia/collapsible-resource-manager/issues/58#issuecomment-882631293).

Override the renderNavigation method in the tool by extending the class:
`new class extends YourTool1 {
            public function renderNavigation(): string
            {
                return '';
            }
        },`
