### ISSUE TITLE
Adding a separator with no link

### ISSUE THREAD

**Issue by omarmatijas** [dcasia/collapsible-resource-manager#49]
I want to customize menu with a separator (not grouping, not new TopLevel item)
For example:

*Admin
   ->Users
   ->Permissions
   / / / / /
   ->Site configuration
   ->Crons jobs

Thanks in advance.

**Comment by NowakAdmin** [comment]
I think You can achieve this by CSS using sidebar nth child

example css (adds 30 px padding after 2nd div ( in sidebar)
  ```
#nova > div > div.flex-none.pt-header.min-h-screen.w-sidebar.bg-grad-sidebar.px-6 > div:nth-child(2)
  {
      padding-bottom: 30px;
  }
```

 for Your example use inspect(F12) and right click desired div then copy selector: 

also You should be able to add extra toplevelresource with no icon (or transparent one) and empty label // not tested
