### ISSUE TITLE
missing style ? 

### ISSUE THREAD

**Issue by breizhwave** [dcasia/collapsible-resource-manager#52]
Hi, I get plus sign on the right and no margin on groups
is that not enough to publish styles ? 
php artisan nova:publish

**Comment by milewski** [comment]
Can you show a screenshoot? it should look like this: 

![image](https://user-images.githubusercontent.com/2874967/114528278-73a47400-9c7b-11eb-8716-36f393e42a12.png)

**Comment by breizhwave** [comment]
Hi thks for yr answer, this is how it looks

![nova-shot](https://user-images.githubusercontent.com/16898162/114529854-ad10bb80-9c4a-11eb-846c-ee17231b2b27.jpg)

**Comment by breizhwave** [comment]
and my packages

 "require": {
        "php": "^7.2",
        "alexbowers/nova-prepopulate-searchable": "^1.0",
        "ampeco/nova-date-range-filter": "^0.1.2",
        "anaseqal/nova-import": "^0.0.2",
        "angauber/nova-select2-filter": "^1.0",
         "digital-creative/clickable-table-row": "^0.1.4",

        "dniccum/nova-documentation": "^1.1",
        "fideloper/proxy": "^4.0",
        "froala/nova-froala-field": "^3.2",
        "google/apiclient": "^2.2",
        "idf/nova-html-card": "^1.2",
        "inani/nova-resource-maker": "^1.0",
        "jackabox/nova-duplicate-field": "^0.3.0",
        "johnathan/nova-trumbowyg": "^1.0",
        "klepak/nova-multiselect-filter": "^1.2",
        "koss-shtukert/laravel-nova-select2-auto-complete": "^1.20",
        "laravel/framework": "^7.5",
        "laravel/nova": "~3.0",
        "laravel/tinker": "^2.4",
        "manogi/nova-tiptap": "^0.3.9",
        "markrassamni/inline-boolean": "^1.0",
        "saumini/count": "^1.0",
        "sloveniangooner/searchable-select": "^1.2",
        "spatie/laravel-tags": "^2.6",
        "spatie/nova-tags-field": "^3.0",
        "square1/nova-metrics": "^1.0",
        "titasgailius/search-relations": "^1.0",
        "wehaa/liveupdate": "^0.1.0"

**Comment by milewski** [comment]
Which browser are you using?

**Comment by breizhwave** [comment]
chrome
