### ISSUE TITLE
how to add items programmatically

### ISSUE THREAD

**Issue by cord** [dcasia/collapsible-resource-manager#6]
Wonder if this would require some development or could already be solved with some code:

How can we add items to the navigation programmatically (eventually through a nova resource)?

**Comment by milewski** [comment]
Uhm... I think the only way you would be able to do this is by updating the config at runtime,

for example:

```php
$configurationKey = 'collapsible-resource-manager.navigation';

config([ $configurationKey => array_merge(config($configurationKey), [ [ 'title' => 'DEMO' ] ]) ]);
```
