### ISSUE TITLE
Add `setBadgeFromResource()` to `NovaResource.php`

### ISSUE THREAD

**Issue by bilogic** [dcasia/collapsible-resource-manager#60]
Hi,

Does it make sense to get the badge from `Resource` as well?
I think it can make `tools()` more readable.

Thank you.

**Comment by milewski** [comment]
Yes would be good, also the badge should have its own API so it can ping the server every X seconds to dynamically update itself whenever needed.. currently, it only gets updated if you do a full page refresh...

**Comment by bilogic** [comment]
Ok, I have never used Vue before, so I probably can't do the part 2. If you are ok, I will do my little part and file a PR for part 1. :)

**Comment by milewski** [comment]
Okay 👍

**Comment by bilogic** [comment]
closed by #61

**Comment by cord** [comment]
> Yes would be good, also the badge should have its own API so it can ping the server every X seconds to dynamically update itself whenever needed.. currently, it only gets updated if you do a full page refresh...

any news for the dynamic update?
