### ISSUE TITLE
Order of default resource manager

### ISSUE THREAD

**Issue by bilogic** [dcasia/collapsible-resource-manager#62]
Hi,

For `disable_default_resource_manager = true`, is there a way currently to show it after our own menus? Thanks.

**Comment by milewski** [comment]
Hey yes.. but you need to sort the Nova::tools property to set the order things.. you can do it from the nova service provider register() method I believe

**Comment by bilogic** [comment]
Hmm, the lifecycle is `register()`, `boot()`, then `NovaApplicationServiceProvider.php::boot()` calls `tools()` and merge it. I don't see a nice, easy way to sort.
