### ISSUE TITLE
Error with 1.4

### ISSUE THREAD

**Issue by cord** [dcasia/collapsible-resource-manager#74]
> DigitalCreative\CollapsibleResourceManager\Resources\Group::DigitalCreative\CollapsibleResourceManager\Resources\{closure}(): Argument #1 ($resource) must be of type string, DigitalCreative\CollapsibleResourceManager\Resources\NovaResource given,

https://github.com/dcasia/collapsible-resource-manager/pull/73/files#r799479628

**Comment by milewski** [comment]
Fixed on [1.4.1](https://github.com/dcasia/collapsible-resource-manager/releases/tag/v1.4.1) can you confirm?

**Comment by cord** [comment]
yes, fixed!
