### ISSUE TITLE
Syntax error with Group (v1.4.0 & v1.4.1)

### ISSUE THREAD

**Issue by Hostbaby75** [dcasia/collapsible-resource-manager#75]
This error message appears when we create a group on the following versions (v1.4.0 & v1.4.1):

syntax error, unexpected '|', expecting variable (T_VARIABLE)

vendor\digital-creative\collapsible-resource-manager\src\Resources\Group.php:13

No problem with version (v1.3.3).

**Comment by milewski** [comment]
Pushed a fix: [v1.4.2](https://github.com/dcasia/collapsible-resource-manager/releases/tag/v1.4.2 ) can you confirm it works

**Comment by Hostbaby75** [comment]
I confirm, the problem has been solved. Thank you.
