### ISSUE TITLE
Change expand and shrink icons

### ISSUE THREAD

**Issue by Abdo-Najjar** [dcasia/collapsible-resource-manager#76]
Is there a way i can changes these icons from (plus and minus) to something else for example arrow up and down?
![image](https://user-images.githubusercontent.com/44542430/152664241-b1fcdbb9-5628-4e1d-b3fe-0c8f4759725b.png)

**Comment by amrhdiab** [comment]
Got the same question too, any luck getting there? I've noticed that the collapsible indicator SVGs are being rendered in `resources/js/components/CollapsibleIndicator.vue`  inside the package vendor directory. Any easy way to override this?

**Comment by milewski** [comment]
I have replaced these icons with chevron on the latest version: [v2.0.0](https://github.com/dcasia/collapsible-resource-manager/releases/tag/v2.0.0)
