### ISSUE TITLE
better understanding of how to use the new badge features to set number from resource?

### ISSUE THREAD

**Issue by vesper8** [dcasia/collapsible-resource-manager#77]
I'm very happy that you added `setBadgeFromResource` but I couldn't find any documentation for it.

In the end I managed to get it to work by adding something like this to my Lens resource:

```

    public static function badge()
    {
        return \App\User::where('status', 'pending')->count();
    }
```

However I am wondering if there's a better way? My lens resource already has this in it:

```

    public static function query(LensRequest $request, $query)
    {
        return $request->withOrdering($request->withFilters(
            $query->select(self::columns())
                ->where('status', 'pending')
        ));
    }
```

So I'm wondering if it's possible to piggy-back off the existing query so that my `public static function badge()` method would be a bit more generic and applicable to all my resources without having to due a standalone count. Is there a way to just get the current resource's count in the badge method?

**Comment by milewski** [comment]
I think you could do this:

```php
public static function badge()
{
    return static::query(request(), \App\User::query());
}
```

Currently, badge functionality has a few issues, like it wont self-update, the only time it refreshes itself is when you do a full page reload... So in the end badge was a feature I was planning to make but never really got a real use case need for myself so have never completed nor documented the existing because it's not great...

**Comment by vesper8** [comment]
Thank you for trying @milewski.

Personally I think this is a great feature, even if it doesn't auto-reload. It really helps my team members know when there are new items that need their attention.

I tried your solution above and unfortunately ran into some issues.

First I tried

```

    public static function badge()
    {
        return static::query($request, \App\User::query());
    }
```

And got 
```

Argument #1 ($request) must be of type Laravel\Nova\Http\Requests\LensRequest, Illuminate\Http\Request given

```


Then  I tried changing the query call from


```


    public static function query(LensRequest $request, $query) { ... }
```

to

```
    public static function query($request, $query) { ... }
```


But then got

```
Method Illuminate\Http\Request::withFilters does not exist.

```

Lastly I tried to inject the `LensRequest $request` in the bade function like this

```

    public static function badge(LensRequest $request)
    {
        return static::query($request, \App\User::query());
    }

```


But then got this


```


Too few arguments to function PendingUsers::badge(), 0 passed in
```

If you have any more ideas on how I can achieve this, would love to hear them!

Thanks!

**Comment by milewski** [comment]
I think you tried everything but what I had suggested 😆 

```php
public static function badge()
{
    return static::query(resolve(LensRequest::class), \App\User::query())->count();
}
```

This `resolve(LensRequest::class)` or `app(LensRequest::class)` this are equivalent, and all it does is resolve the request LensRequest::class from the container as is what your query() method needs...

**Comment by vesper8** [comment]
whaaat.. that was in your comment?? lol.. I don't even know what might have happened there.. I could swear I copy/pasted your code.. clearly I didn't.. my bad! This `resolve()` trick seems very useful and I wasn't aware you could do that. Thank you : ) I'll give that a try

**Comment by vesper8** [comment]
Ahhhh... I see now.. your initial comment did not have the `resolve` in it! I copy/pasted your code from your original comment which was sent to my email ;p You sneaked it in there afterwards and I didn't notice ;)
