### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by shazibrazzaq** [dcasia/collapsible-resource-manager#8]
Is there any way we can implement permission via policies so it doesn't show links not allowed to users with certain roles i am using Spatie permission package?

**Comment by milewski** [comment]
I have completed forgotten about that... I will update it

**Comment by milewski** [comment]
Hi @shazibrazzaq , currently the permissions were already being respected, however, the menu would still be shown even if the resources list was empty, I fixed it on version [v0.1.6](https://github.com/dcasia/collapsible-resource-manager/releases/tag/v0.1.6)

**Comment by shazibrazzaq** [comment]
Thanks its good now. i have another thing i noticed may be you can guide me if i am wrong i will post another issue for it.
