### ISSUE TITLE
Nova 4 compatibility

### ISSUE THREAD

**Issue by jsznap** [dcasia/collapsible-resource-manager#83]
A few breaking changes in Nova 4.

**Comment by milewski** [comment]
Is this package still needed now that nova 4 provides a better way to define menu/icons compared to v3?

**Comment by NowakAdmin** [comment]
It will be great to update compatibility just for people who update existing nova projects from v3 to v4

error that shows up for me:

    Class DigitalCreative\CollapsibleResourceManager\CollapsibleResourceManager contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Laravel\Nova\Tool::menu)

**Comment by scramatte** [comment]
+1 here too ...

**Comment by FSElias** [comment]
+1

**Comment by vesper8** [comment]
@milewski this package is widely used. I've built on top of it a lot for many projects. I feel like if it's simple to upgrade to Nova V4.. and judging from that error, it looks like it indeed may be simple, then for that reason alone I think it should be upgraded.

While some of the things may now be available out-of-the-box... it's kind of a big job to migrate a project that makes heavy use of `digital-creative/collapsible-resource-manager`

**Comment by vesper8** [comment]
@workupsrl @rklugman @marispro

I see that all three of you forked this package and attempted to add support for Nova V4. I tried all of your forks, and while they make the error go away, I can't get my navigation to actually appear.. were any of you successful?

**Comment by marispro** [comment]
@vesper8 
> I see that all three of you forked this package and attempted to add support for Nova V4. I tried all of your forks, and while they make the error go away, I can't get my navigation to actually appear.. were any of you successful?

We decided to use Nova 4 built in functionality for now, actually waiting for update. Still busy with other packages to maintain and upgrade for nova 4 :)

**Comment by wajdijurry** [comment]
+1

**Comment by wajdijurry** [comment]
> It will be great to update compatibility just for people who update existing nova projects from v3 to v4
> 
> error that shows up for me:
> 
> ```
> Class DigitalCreative\CollapsibleResourceManager\CollapsibleResourceManager contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Laravel\Nova\Tool::menu)
> ```

I have the same error, I will fork and create a PR

**Comment by wajdijurry** [comment]
**Update:** Laravel Nova 4.x supports menu grouping:
https://nova.laravel.com/docs/customization/menus.html#customizing-the-main-menu

**Comment by milewski** [comment]
I started to work on an upgrade for this package, but I'm unsure if I should rename the package... or still keep it called `collapsible-resource-manager` since the "core feature" collapsible menu is already supported by Nova 4 out of the box... this is a quick preview of how the new version will look like:

https://github.com/dcasia/collapsible-resource-manager/assets/2874967/b9b28b2f-6802-421e-a64f-a0f597f3a4ee

**Comment by wajdijurry** [comment]
> I started to work on an upgrade for this package, but I'm unsure if I should rename the package... or still keep it called `collapsible-resource-manager` since the "core feature" collapsible menu is already supported by Nova 4 out of the box... this is a quick preview of how the new version will look like:
> 
>  20231006-201214.mp4

It's great from first POV. I just wanna know how could you add horizontal tabs inside the container and on the listing view?

**Comment by milewski** [comment]
> It's great from first POV. I just wanna know how could you add horizontal tabs inside the container and on the listing view?

These are other packages:

https://github.com/dcasia/resource-navigation-tab
https://github.com/dcasia/resource-navigation-link

**Comment by milewski** [comment]
Done, now latest version ([v2.0.0](https://github.com/dcasia/collapsible-resource-manager/releases/tag/v2.0.0)) works in nova 4!
