### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by shazibrazzaq** [dcasia/collapsible-resource-manager#9]
You are using trans function for the translations, it's not working with my nova. 2.1.1 
but if i user __() it works, can you guide me if i am wrongly using it?

i am using it like here

https://nova.laravel.com/docs/1.0/customization/localization.html#overview

sv.json i have. Can you please guide?

**Comment by milewski** [comment]
First, you need to enable it in the configuration `'translate_title' => true,`

and then every title will be auto-translated,  

```php
'navigation' => [
        [
            'title' => 'Resource Title', // this will auto transform into __('Resource Title')
             .....
            'groups' => [
                [
                    'title' => 'Assets',  /// and __('Assets)
                     ....                  
                ]
            ]
        ]
    ]
```

however you resource class still needs to be translated through the static name method:

```php
    /**
     * Get the displayable label of the resource.
     *
     * @return string
     */
    public static function label()
    {
        return __('Pages');
    }
```

**Comment by shazibrazzaq** [comment]
yes i am doing exactly like you suggested. 

I meant on this function in your file CollapsibleResourceManager.php
private function translateKey(?string $key): string
```
    {

        if ($key && config('collapsible-resource-manager.translate_title', false)) {

            return trans($key);

        }

        return $key;

    }
```

If i replace trans with __() it works, otherwise it doesn't translate. I think we need to replace this function in the function so it works for nova. If there anything else i am missing please let me know.

**Comment by milewski** [comment]
I'm not sure what's going on, if you see the `__()` function it is just calling `trans()` behind the scenes

```
if (! function_exists('__')) {
    /**
     * Translate the given message.
     *
     * @param  string|null  $key
     * @param  array  $replace
     * @param  string|null  $locale
     * @return \Illuminate\Contracts\Translation\Translator|string|array|null
     */
    function __($key = null, $replace = [], $locale = null)
    {
        if (is_null($key)) {
            return $key;
        }

        return trans($key, $replace, $locale);
    }
}
```

And just to confirm are updating the right file?

![image](https://user-images.githubusercontent.com/2874967/66729995-5a054f00-ee81-11e9-8b04-929200ac0262.png)

**Comment by shazibrazzaq** [comment]
![image](https://user-images.githubusercontent.com/7521588/66755431-60132400-eeb1-11e9-80ab-d8dd1a0766ac.png)

i tried all three paths issue is still there.. but as soon i replace trans function with __() it works.

In nova docs they have mentioned to use __() function here is the reference.

https://nova.laravel.com/docs/2.0/customization/localization.html#overview

My suggestion is we can change to __() instead of trans() if it's ok with you. And i can update from code otherwise i think i can extend class and override the function. But it will help others if we change in the package class itself.

**Comment by milewski** [comment]
I just pushed a new version `v0.1.7` that uses `__()` instead of `trans` see if works for you. 

This issue is very odd because I'm personally using this package and having multi-language in Chinese/English and it works fine with trans(), perhaps it`s your nova version? currently im `2.4.0` and laravel 6

**Comment by shazibrazzaq** [comment]
Thanks a lot, it worked for me. 

Yes i also find it strange i have nova 2.4.0 too only difference is laravel 5.8.* but still it should be working it's for you.

Anyway thanks it worked for me now.
